export const BITSClg = [
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Chemical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "224",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Civil",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "213",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Electrical & Electronics",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "272",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Mechanical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "244",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Computer Science",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "331",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Electronics & Instrumentation",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "266",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Electronics & Communication",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "296",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Manufacturing",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "220",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Pharm",
    duration: "4 Years",
    Degree_Type: "B.Pharm",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "153",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Biological Sciences",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "212",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Chemistry",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "213",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Economics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "257",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Mathematics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "236",
  },
  {
    Institute: "BITS-Pilani ",
    Academic_Program_Name: "Physics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "235",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Chemical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "209",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Electrical & Electronics",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "252",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Mechanical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "223",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Computer Science",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "295",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Electrical & Instrumentation",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "244",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Electrical & Communication",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "267",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Biological Sciences",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "204",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Chemistry",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "205",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Economics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "239",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Mathematics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "221",
  },
  {
    Institute: "BITS-Goa ",
    Academic_Program_Name: "Physics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "222",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Chemical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "207",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Civil",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "204",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Electrical & Electronics",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "251",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Mechanical",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "218",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Computer Science",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "284",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Electronics & Instrumentation",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "244",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Electronics & Communication",
    duration: "4 Years",
    Degree_Type: "BE",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "265",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Pharm",
    duration: "4 Years",
    Degree_Type: "B.Pharm",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "135",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Biological Sciences",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "204",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Chemistry",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "205",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Economics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "236",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Mathematics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "219",
  },
  {
    Institute: "BITS-Hyderabad ",
    Academic_Program_Name: "Physics",
    duration: "5 Years",
    Degree_Type: "BE + M.Sc.",
    Quota: "AI",
    Seat_Type: "OPEN",
    Gender: "Gender-Neutral",
    Closing_Rank: "219",
  },
  
];
