export const iits = [
  {shortName:'All'},
  {name:'Indian Institute  of Technology Bhubaneswar' , shortName: 'IIT-Bhubaneswar'},
  {name:'Indian Institute  of Technology Bombay' , shortName : 'IIT-Bombay'},
  {name:'Indian Institute  of Technology Mandi' , shortName : 'IIT-Mandi'},
  {name:'Indian Institute  of Technology Delhi' , shortName : 'IIT-Delhi'},
  {name:'Indian Institute  of Technology Indore' , shortName :'IIT-Indore'},
  {name:'Indian Institute  of Technology Kharagpur' , shortName : 'IIT-Kharagpur'},
  {name:'Indian Institute  of Technology Hyderabad' , shortName : 'IIT-Hyderabad'},
  {name:'Indian Institute  of Technology Jodhpur' , shortName : 'IIT-Jodhpur'},
  {name:'Indian Institute  of Technology Kanpur' , shortName : 'IIT-Kanpur'},
  {name:'Indian Institute  of Technology Madras' , shortName : 'IIT-Madras'},
  {name:'Indian Institute  of Technology Gandhinagar' , shortName : 'IIT-Ghandhinagar'},
  {name:'Indian Institute  of Technology Patna' , shortName : 'IIT-Patna'},
  {name:'Indian Institute  of Technology Roorkee' , shortName :'IIT-Roorkee'},
  {name:'Indian Institute  of Technology (ISM) Dhanbad' , shortName : 'IIT-(ISM)Dhanbad'},
  {name:'Indian Institute  of Technology Ropar', shortName:'IIT-Ropar'},
  {name:'Indian Institute  of Technology (BHU) Varanasi' , shortName : 'IIT-(BHU)Varanasi'},
  {name:'Indian Institute  of Technology Guwahati' , shortName :'IIT-Guwahati'},
  {name:'Indian Institute of Technology Bhilai' , shortName : 'IIT-Bhilai'},
  {name:'Indian Institute of Technology Goa', shortName :'IIT-Goa'},
  {name:'Indian Institute  of Technology Palakkad' , shortName :'IIT-Palakkad'},
  {name:'Indian Institute  of Technology Tirupati' , shortName : 'IIT-Tirupati'},
  {name:'Indian Institute of Technology Jammu' , shortName : 'IIT-Jammu'},
  {name:'Indian Institute of Technology Dharwad' , shortName : 'IIT-Dharwad'},

]

export const nits = [
    'All',
    'Dr. B R Ambedkar National Institute of Technology Jalandhar',
    'Malaviya National Institute of Technology Jaipur',
    'Maulana Azad National Institute of Technology Bhopal',
    'Motilal Nehru National Institute of Technology Allahabad',
    'National Institute of Technology  Agartala',
    'National Institute of Technology Calicut',
    'National Institute of Technology Delhi',
    'National Institute of Technology Durgapur',
    'National Institute of Technology Goa',
    'National Institute of Technology Hamirpur',
    'National Institute of Technology Karnataka Surathkal',
    'National Institute of Technology Meghalaya',
    'National Institute of Technology Nagaland',
    'National Institute of Technology Patna',
    'National Institute of Technology Puducherry',
    'National Institute of Technology Raipur',
    'National Institute of Technology Sikkim',
    'National Institute of Technology Arunachal Pradesh',
    'National Institute of Technology Jamshedpur',
    'National Institute of Technology Kurukshetra',
    'National Institute of Technology Manipur',
    'National Institute of Technology Mizoram',
    'National Institute of Technology Rourkela',
    'National Institute of Technology Silchar',
    'National Institute of Technology Srinagar',
    'National Institute of Technology Tiruchirappalli',
    'National Institute of Technology Uttarakhand',
    'National Institute of Technology Warangal',
    'Sardar Vallabhbhai National Institute of Technology Surat',
    'Visvesvaraya National Institute of Technology Nagpur',
    'National Institute of Technology Andhra Pradesh',
  ]


export const iiits = [
  'ALL',
  'Atal Bihari Vajpayee Indian Institute of Information Technology  Management Gwalior',
  'Indian Institute of Information Technology (IIIT)Kota Rajasthan',
  'Indian Institute of Information Technology Guwahati',
  'Indian Institute of Information Technology(IIIT) Kalyani West Bengal',
  'Indian Institute of Information Technology(IIIT) Kilohrad Sonepat Haryana',
  'Indian Institute of Information Technology(IIIT) Una Himachal Pradesh',
  'Indian Institute of Information Technology (IIIT) Sri City Chittoor',
  'Indian Institute of Information Technology(IIIT) Vadodara Gujrat',
  'Indian Institute of Information Technology Allahabad',
  'Indian Institute of Information Technology Design  Manufacturing Kancheepuram',
  'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology Design  Manufacture Jabalpur',
  'Indian Institute of Information Technology  Manipur',
  'Indian Institute of Information Technology Tiruchirappalli',
  'Indian Institute of Information Technology Lucknow',
  'Indian Institute of Information Technology(IIIT) Dharwad',
  'Indian Institute of Information Technology Design  Manufacturing Kurnool Andhra Pradesh',
  'Indian Institute of Information Technology(IIIT) Kottayam',
  'Indian Institute of Information Technology (IIIT) Ranchi',
  'Indian Institute of Information Technology (IIIT) Nagpur',
  'Indian Institute of Information Technology (IIIT) Pune',
  'Indian Institute of Information Technology Bhagalpur',
  'Indian Institute of Information Technology Bhopal',
  'Indian Institute of Information Technology Surat',
  'Indian Institute of Information Technology Agartala',
  'Indian institute of information technology Raichur Karnataka',
  'Indian Institute of Information Technology Vadodara International Campus Diu (IIITVICD)',


]  


export const GFTI = [
  'ALL',
  'Indian Institute of Engineering Science and Technology Shibpur',
  'Assam University Silchar',
  'Birla Institute of Technology Mesra  Ranchi',
  'Gurukula Kangri Vishwavidyalaya Haridwar',
  'Indian Institute of Carpet Technology Bhadohi',
  'Institute of Infrastructure Technology Research and Management-Ahmedabad',
  'Institute of Technology Guru Ghasidas Vishwavidyalaya (A Central University) Bilaspur (C.G.)',
  'J.K. Institute of Applied Physics  Technology Department of Electronics  Communication University of Allahabad- Allahabad',
  'National Institute of Electronics and Information Technology Aurangabad (Maharashtra)',
  'National Institute of Advanced Manufacturing Technology Ranchi',
  'Sant Longowal Institute of Engineering and Technology',
  'Mizoram University Aizawl',
  'School of Engineering Tezpur University Napaam Tezpur',
  'School of Planning  Architecture Bhopal',
  'School of Planning  Architecture New Delhi',
  'School of Planning  Architecture: Vijayawada',
  'Shri Mata Vaishno Devi University Katra Jammu Kashmir',
  'International Institute of Information Technology Naya Raipur',
  'University of Hyderabad',
  'Punjab Engineering College Chandigarh',
  'Jawaharlal Nehru University Delhi',
  'International Institute of Information Technology Bhubaneswar',
  'Central institute of Technology Kokrajar Assam',
  'Puducherry Technological University Puducherry',
  'Ghani Khan Choudhary Institute of Engineering and Technology Malda West Bengal',
  'Central University of Rajasthan Rajasthan',
  'National Institute of Food Technology Entrepreneurship and Management Kundli',
  'National Institute of Food Technology Entrepreneurship and Management Thanjavur',
  'North Eastern Regional Institute of Science and Technology Nirjuli-791109 (Itanagar)',
  'Indian Institute of Handloom Technology(IIHT) Varanasi',
  'Chhattisgarh Swami Vivekanada Technical University Bhilai (CSVTU Bhilai)',
  'Institute of Chemical Technology Mumbai: Indian Oil Odisha Campus Bhubaneswar',
  'North-Eastern Hill University Shillong',
  'Central University of Jammu',
  'Institute of Engineering and Technology Dr. H. S. Gour University. Sagar (A Central University)',
  'Central University of Haryana',
  'Birla Institute of Technology Deoghar Off-Campus',
  'Birla Institute of Technology Patna Off-Campus',
  'Indian Institute of Handloom Technology Salem',

]
  

export const JAC = [
  {shortName:'ALL'},
  {name:'Delhi Technological University', shortName:'DTU'},
  {name:'Netaji Subash University of Technology', shortName:'NSUT'},
  {name:'Indraprasth Institute of Technology Delhi', shortName:'IIIT-Delhi'},
  {name:'Indira Gandhi Delhi Technical University for Women', shortName:'IGDTUW-Delhi'},
  {name:'Delhi Skill and Entrepreneurship University', shortName:'DSEU-Delhi'}

]

export const BITS = [
  'ALL',
  'BITS-Pilani',
  'BITS-Goa',
  'BITS-Hyderabad'
]